name: 'Validate Flux Helm Release'
description: 'Github Action to validate Flux Helm Releases with kubeval'
author: 'Stefan Prodan'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  helmRelease:
    description: 'The HelmRelease YAML file path or dir'
    required: true
  ignoreValues:
    description: 'When set to true HelmRelease values will be ignored'
    default: 'false'
  kubernetesVersion:
    description: 'Version of Kubernetes to validate against'
    default: 'master'
  helmVersion:
    description: 'Version of Helm to validate against'
    default: 'v2'
  awsS3Repo:
    description: '(Optional) Set to true if using an AWS S3 Helm Repo'
    default: false
  awsS3RepoName:
    description: '(Optional) The name of the AWS S3 Helm repo, if awsS3Repo was set to true'
    default: ''
  awsS3Plugin:
    description: '(Optional) AWS S3 Plugin to be used in the helm plugin install command'
    default: ''
  helmSourcesCacheEnabled:
    description: '(Optional) Enabled Helm source caching, so same release or ref will not be downloaded twice.'
    default: 'false'
  valuesFromDir:
    description: '(Optional) Path to directory with configMaps and secrets used in HelmRelease with valuesFrom'
    required: false
    default: ''

outputs:
  numFilesTested:
    description: The number of HelmRelease files which were tested

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.helmRelease }}
    - ${{ inputs.ignoreValues }}
    - ${{ inputs.kubernetesVersion }}
    - ${{ inputs.helmVersion }}
    - ${{ inputs.awsS3Repo }}
    - ${{ inputs.awsS3RepoName }}
    - ${{ inputs.awsS3RepoPlugin }}
    - ${{ inputs.helmSourcesCacheEnabled }}
    - ${{ inputs.valuesFromDir }}