name: PUSH

on: [push]

jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.7
        with:
          name: casestack/hrval
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
